export const FETCH_CUSTUMERS = 'FETCH_CUSTUMERS';
export const UPDATE_CUSTUMERS = 'UPDATE_CUSTUMERS';
export const INSERT_CUSTUMERS = 'INSERT_CUSTUMERS';
export const DELETE_CUSTUMER = 'DELETE_CUSTUMER';
